# Generated by Django 3.0.4 on 2020-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField(blank=True)),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('data', models.TextField(blank=True)),
            ],
        ),
    ]
